# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: robotics010/cycleon

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Tools version
        run: |
          python3 --version
          cmake --version
          g++ --version

      - name: Build service
        run: |
          echo Build service
          cd service
          cmake -S . -B build
          cmake --build build

      - name: Test service
        run: |
          echo Test service
          cd service
          cd build && ctest

      - name: Build cli-tool
        run: |
          echo Build cli-tool
          cd cli_tool
          python3 -m build

      - name: Test cli-tool
        run: |
          echo Test cli-tool
          cd cli_tool
          python3 -m pytest test/
